#
# http://generatory.it/
#

[ksef]
version = test

[firma1]
nip = 3750687646
nazwa = Usługi informatyczne Jan Kowalski
adres = Jana Matejki 3, 00-001 Warszawa

pesel = 27102865953
imie = Jan
nazwisko = Kowalski

[firma2]
nip = 8387904056
nazwa = Usługi informatyczne Jan Kowalski
adres = Jana Matejki 4, 00-001 Warszawa

pesel = 59112002194
imie = Jan
nazwisko = Kowalski

[test]
url = https://ksef-test.mf.gov.pl

[demo]
url = https://ksef-demo.mf.gov.pl

[prod]
url = https://ksef-prod.mf.gov.pl
