#!/bin/bash
download(){
    wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.0.1/openapi-generator-cli-7.0.1.jar -O openapi-generator-cli.jar
    #curl https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/bin/utils/openapi-generator-cli.sh > openapi-generator-cli
}

one(){
java \
  -Xms512M                        \
  -Xmx1024M                       \
  -server                         \
  -jar openapi-generator-cli.jar $*
}

xoneline(){
    one generate -g python -i ../KSeF-online.yaml -o xx/
}

#$*
xoneline
